### ISSUE TITLE
Demo site: incorrect CSS gets loaded

### ISSUE THREAD

**Issue by GreatEmerald** [ashutosh2k12/hcz-jekyll-blog#15]
Since the rewrite, the `_config.yml` file has had more generic options, and no longer has a filled-in `baseurl` variable. That causes the demo site to load the CSS of the parent site instead.

That said, you have a `master` branch, but it's empty right now. Why not separate everything into a clean `master` branch, and a demo site `gh-pages` branch? That would cut down on the merge conflicts that currently happen every time `_config.yml` changes.

**Comment by ashutosh2k12** [comment]
Thanks @GreatEmerald for the idea. Currently, I am not getting much time but I will try to do this tonight

**Comment by ashutosh2k12** [comment]
CSS issue is fix in recent commit. Taking your suggestions, I have made a master branch now for further commits and pulls. gh-pages will now act only for demo site reflection.

**Comment by GreatEmerald** [comment]
Nice. You might also want to set the master branch as default.
