### ISSUE TITLE
Publish as jekyll theme

### ISSUE THREAD

**Issue by brutalcrozt** [ashutosh2k12/hcz-jekyll-blog#22]
I hope that your work can be installed automatically with adding gem, as described [here](https://jekyllrb.com/docs/themes/#installing-a-theme). If you feel it necessary maybe this can be your reminder, but feel free to close it if you think it's not necessary. Thanks i love your theme :smile:

**Comment by ashutosh2k12** [comment]
Thanks for the idea but its not going to be happening soon from my side. I will be releasing v2 for this theme with this support, since I had this approach from very begining. I am all ears for any suggestions.
Thanks for loving the theme.
