### ISSUE TITLE
navigation.html: allow specifying target

### ISSUE THREAD

**Issue by GreatEmerald** [ashutosh2k12/hcz-jekyll-blog#6]
Right now there's no way to make a menu link open in a new tab, even though that's the expected behaviour of the "XML Feed" link.

Adding this into `_includes/navigation.html` seems to do the job decently fine, although perhaps making a more user-friendly boolean is a better idea:
```
        {% assign target = i.target %}
        {% unless target %} {% assign target = '_self' %} {% endunless %}
```

**Comment by ashutosh2k12** [comment]
Thanks for idea. Updated the repo in https://github.com/ashutosh2k12/hcz-jekyll-blog/commit/2e964dd322ddf79165f404be11bc875bd67f620a
