### ISSUE TITLE
How to use this theme?

### ISSUE THREAD

**Issue by miaochiahao** [ashutosh2k12/hcz-jekyll-blog#9]
Hello, my friend wants to use the theme. But after she forked your repository and changed the name to "celery-gu.github.io", she cannot visit the website "celery-gu.github.io". And I tried like that and found I can't make it either. Could you please tell me how to use it? Thank you very much.

**Comment by ashutosh2k12** [comment]
Can you point me to the repo so I can have a look (if thats not a private repo)

**Comment by miaochiahao** [comment]
Sure! Thanks a lot. The address is https://github.com/celery-gu/celery-gu.github.io
So the github pages address is supposed to be celery-gu.github.io
Right?

**Comment by Nikitaw99** [comment]
@miaochiahao Unless a `CNAME` (custom domain name) is specified.

**Comment by Nikitaw99** [comment]
celery-gu/celery-gu.github.io#1
Here's the PR I made to fix it.

**Comment by ashutosh2k12** [comment]
Closing this issue for now. Let me know if issue is still there and I will re-open

**Comment by miaochiahao** [comment]
It works ! Thanks for all !!
